// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Utils from "../Utils.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function Editor(props) {
  var onChange = props.onChange;
  var phase = props.phase;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("img", {
                              src: Utils.toStr(phase) === Utils.toStr("Work") ? "src/styles/work.svg" : "src/styles/break.svg"
                            }),
                        JsxRuntime.jsx("span", {
                              children: Utils.toStr(phase)
                            })
                      ],
                      className: "text-2xl font-body flex justify-center items-center gap-4"
                    }),
                JsxRuntime.jsx("input", {
                      className: "text-center py-2 rounded-md font-mono",
                      type: "number",
                      value: String(props.value),
                      onChange: (function ($$event) {
                          Curry._1(onChange, $$event.target.value);
                        })
                    })
              ],
              className: "flex flex-col gap-4"
            });
}

var make = Editor;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
