// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils from "../Utils.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function getDashArray(seconds, maxTime) {
  var reminder = seconds / maxTime;
  var timeStr = String(reminder * 283.0 | 0);
  var strokeDasharray = timeStr + " 283";
  return {
          strokeDasharray: strokeDasharray
        };
}

function Timer(props) {
  var seconds = props.seconds;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("svg", {
                      children: JsxRuntime.jsxs("g", {
                            children: [
                              JsxRuntime.jsx("circle", {
                                    className: "timer-path-gray",
                                    cx: "50",
                                    cy: "50",
                                    r: "45"
                                  }),
                              JsxRuntime.jsx("path", {
                                    className: "timer-path-red",
                                    style: getDashArray(seconds, props.maxTime),
                                    d: "\n                        M 50, 50\n                        m -45, 0\n                        a 45,45 0 1,0 90,0\n                        a 45,45 0 1,0 -90,0\n                        ",
                                    strokeDasharray: "283"
                                  })
                            ],
                            className: "timer-circle"
                          }),
                      className: "timer-svg",
                      viewBox: "0 0 100 100"
                    }),
                JsxRuntime.jsx("span", {
                      children: Utils.toStr(Utils.formatTime(seconds)),
                      className: "timer-label"
                    })
              ],
              className: "timer"
            });
}

var make = Timer;

export {
  getDashArray ,
  make ,
}
/* react/jsx-runtime Not a pure module */
