// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as JsxRuntime from "react/jsx-runtime";

function Header(props) {
  var currentPhase = props.currentPhase;
  var dispatch = props.dispatch;
  var label = props.seconds > 0 ? (
      currentPhase ? "Break Time" : "Work Time"
    ) : (
      currentPhase ? "Ready for a break?" : "Ready to Work??"
    );
  return JsxRuntime.jsx("h1", {
              children: label,
              className: "text-2xl lg:text-3xl font-body cursor-pointer text-red-600",
              onClick: currentPhase === /* Work */0 ? (function (param) {
                    Curry._1(dispatch, /* TogglePhase */4);
                  }) : (function (param) {
                    Curry._1(dispatch, /* TogglePhase */4);
                  })
            });
}

var make = Header;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
