// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils from "./Utils.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function Editor(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("span", {
                      children: Utils.toStr(props.phase)
                    }),
                JsxRuntime.jsx("input", {
                      type: "number",
                      value: String(props.value)
                    })
              ]
            });
}

var make = Editor;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
