// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils from "./Utils.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function Timer(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("span", {
                    children: Utils.toStr(Utils.formatTime(props.seconds))
                  })
            });
}

var make = Timer;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
