// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_format from "rescript/lib/es6/caml_format.js";

function toStr(str) {
  return str;
}

function padNumber(num) {
  if (Caml_format.int_of_string(num) < 10) {
    return "0" + num;
  } else {
    return num;
  }
}

function formatTime(seconds) {
  var mins = seconds / 60 | 0;
  var secs = seconds % 60;
  var minStr = padNumber(String(mins));
  var secStr = padNumber(String(secs));
  return minStr + ":" + secStr;
}

export {
  toStr ,
  padNumber ,
  formatTime ,
}
/* No side effect */
