// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as State from "./components/State/State.bs.js";
import * as Timer from "./components/Timer/Timer.bs.js";
import * as React from "react";
import * as Editor from "./components/Editor/Editor.bs.js";
import * as Header from "./components/Header/Header.bs.js";
import * as Actions from "./components/Actions/Actions.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

import './styles/App.css';
;

function App(props) {
  var match = React.useReducer(State.reducer, State.initialState);
  var dispatch = match[1];
  var state = match[0];
  React.useEffect((function () {
          var timer = setInterval((function (param) {
                  Curry._1(dispatch, /* Tick */3);
                }), 1000);
          return (function (param) {
                    clearInterval(timer);
                  });
        }), []);
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(Header.make, {
                      seconds: state.seconds,
                      dispatch: dispatch,
                      currentPhase: state.currentPhase
                    }),
                JsxRuntime.jsx(Timer.make, {
                      seconds: state.seconds
                    }),
                JsxRuntime.jsx(Actions.make, {
                      dispatch: dispatch,
                      isTicking: state.isTicking
                    }),
                JsxRuntime.jsx(Editor.make, {
                      phase: "work",
                      value: state.workTime,
                      onChange: (function (e) {
                          Curry._1(dispatch, /* SetTime */{
                                _0: /* Work */0,
                                _1: e
                              });
                        })
                    }),
                JsxRuntime.jsx(Editor.make, {
                      phase: "play",
                      value: state.playTime,
                      onChange: (function (e) {
                          Curry._1(dispatch, /* SetTime */{
                                _0: /* Play */1,
                                _1: e
                              });
                        })
                    })
              ],
              className: "flex flex-col items-center justify-center h-screen bg-gray-100"
            });
}

var make = App;

export {
  make ,
}
/*  Not a pure module */
