// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as State from "./components/State.bs.js";
import * as Timer from "./components/Timer.bs.js";
import * as React from "react";
import * as Editor from "./components/Editor.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  var match = React.useReducer(State.reducer, State.initialState);
  var dispatch = match[1];
  var state = match[0];
  React.useEffect((function () {
          var timer = setInterval((function (param) {
                  Curry._1(dispatch, /* Tick */3);
                }), 1000);
          return (function (param) {
                    clearInterval(timer);
                  });
        }), []);
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("button", {
                      children: "Switch timer",
                      onClick: (function (param) {
                          Curry._1(dispatch, /* TogglePhase */4);
                        })
                    }),
                JsxRuntime.jsx(Timer.make, {
                      seconds: state.seconds
                    }),
                JsxRuntime.jsx("button", {
                      children: "Start",
                      onClick: (function (param) {
                          Curry._1(dispatch, /* Start */0);
                        })
                    }),
                JsxRuntime.jsx("button", {
                      children: "Stop",
                      onClick: (function (param) {
                          Curry._1(dispatch, /* Stop */1);
                        })
                    }),
                JsxRuntime.jsx("button", {
                      children: "Reset",
                      onClick: (function (param) {
                          Curry._1(dispatch, /* Reset */2);
                        })
                    }),
                JsxRuntime.jsx(Editor.make, {
                      phase: "work",
                      value: state.workTime,
                      onChange: (function (e) {
                          Curry._1(dispatch, /* SetTime */{
                                _0: /* Work */0,
                                _1: e
                              });
                        })
                    }),
                JsxRuntime.jsx(Editor.make, {
                      phase: "play",
                      value: state.playTime,
                      onChange: (function (e) {
                          Curry._1(dispatch, /* SetTime */{
                                _0: /* Play */1,
                                _1: e
                              });
                        })
                    })
              ]
            });
}

var make = App;

export {
  make ,
}
/* Timer Not a pure module */
