// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as State from "./components/State/State.bs.js";
import * as Timer from "./components/Timer/Timer.bs.js";
import * as React from "react";
import * as Editor from "./components/Editor/Editor.bs.js";
import * as Header from "./components/Header/Header.bs.js";
import * as Actions from "./components/Actions/Actions.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

import './styles/App.css';
;

function App(props) {
  var match = React.useReducer(State.reducer, State.initialState);
  var dispatch = match[1];
  var state = match[0];
  React.useEffect((function () {
          var timer = setInterval((function (param) {
                  Curry._1(dispatch, /* Tick */3);
                }), 1000);
          return (function (param) {
                    clearInterval(timer);
                  });
        }), []);
  var match$1 = state.currentPhase;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "Pomodoro Timer",
                      className: "text-3xl lg:text-5xl font-body"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx(Header.make, {
                                      seconds: state.seconds,
                                      dispatch: dispatch,
                                      currentPhase: state.currentPhase
                                    }),
                                JsxRuntime.jsx(Timer.make, {
                                      seconds: state.seconds,
                                      maxTime: match$1 ? Math.imul(state.playTime, 60) : Math.imul(state.workTime, 60)
                                    }),
                                JsxRuntime.jsx(Actions.make, {
                                      dispatch: dispatch,
                                      isTicking: state.isTicking
                                    })
                              ],
                              className: "flex flex-col items-center gap-6"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx(Editor.make, {
                                      phase: "Work",
                                      value: state.workTime,
                                      onChange: (function (e) {
                                          Curry._1(dispatch, /* SetTime */{
                                                _0: /* Work */0,
                                                _1: e
                                              });
                                        })
                                    }),
                                JsxRuntime.jsx(Editor.make, {
                                      phase: "Break",
                                      value: state.playTime,
                                      onChange: (function (e) {
                                          Curry._1(dispatch, /* SetTime */{
                                                _0: /* Play */1,
                                                _1: e
                                              });
                                        })
                                    })
                              ],
                              className: "flex flex-col justify-center gap-6"
                            })
                      ],
                      className: "flex flex-col lg:flex-row justify-center gap-10"
                    })
              ],
              className: "flex flex-col gap-5 p-8 lg:py-12 lg:px-40 lg:mx-28 lg:my-14 items-center justify-center bg-red-200 rounded-2xl shadow-lg"
            });
}

var make = App;

export {
  make ,
}
/*  Not a pure module */
