// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.bs.js";
import * as React from "react";
import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Client from "react-dom/client";
import * as JsxRuntime from "react/jsx-runtime";

var root = document.querySelector("#root");

if (root == null) {
  Js_exn.raiseError("Root not found!");
} else {
  Client.createRoot(root).render(JsxRuntime.jsx(React.StrictMode, {
            children: JsxRuntime.jsx(App.make, {})
          }));
}

var root$1 = (root == null) ? undefined : Caml_option.some(root);

export {
  root$1 as root,
}
/* root Not a pure module */
