// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as JsxRuntime from "react/jsx-runtime";

function Actions(props) {
  var dispatch = props.dispatch;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("button", {
                      children: JsxRuntime.jsx("img", {
                            src: "src/styles/reset.svg"
                          }),
                      className: "flex justify-center items-center bg-red-500 px-4 py-3 rounded-2xl gap-2 shadow-md",
                      onClick: (function (param) {
                          Curry._1(dispatch, /* Reset */2);
                        })
                    }),
                props.isTicking ? JsxRuntime.jsx("button", {
                        children: JsxRuntime.jsx("img", {
                              src: "src/styles/stop.svg"
                            }),
                        className: "flex justify-center items-center bg-red-500 px-4 py-3 rounded-2xl gap-2 shadow-md",
                        onClick: (function (param) {
                            Curry._1(dispatch, /* Stop */1);
                          })
                      }) : JsxRuntime.jsx("button", {
                        children: JsxRuntime.jsx("img", {
                              src: "src/styles/start.svg"
                            }),
                        className: "flex justify-center items-center bg-red-500 px-4 py-3 rounded-2xl gap-2 shadow-md",
                        onClick: (function (param) {
                            Curry._1(dispatch, /* Start */0);
                          })
                      })
              ],
              className: "flex gap-10"
            });
}

var make = Actions;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
